LOAD DATA LOCAL INFILE "type.dat"
INTO TABLE Type
FIELDS TERMINATED BY "<>";

LOAD DATA LOCAL INFILE "user.dat"
INTO TABLE Userdb
FIELDS TERMINATED BY "<>";

LOAD DATA LOCAL INFILE "parents.dat"
INTO TABLE Parents
FIELDS TERMINATED BY "<>";

LOAD DATA LOCAL INFILE "class.dat"
INTO TABLE Class
FIELDS TERMINATED BY "<>";

LOAD DATA LOCAL INFILE "teacher.dat"
INTO TABLE Teacher
FIELDS TERMINATED BY "<>";

LOAD DATA LOCAL INFILE "nutritionist.dat"
INTO TABLE Nutritionist
FIELDS TERMINATED BY "<>";

LOAD DATA LOCAL INFILE "kid_basicinfo.dat"
INTO TABLE Kid_basicINFO
FIELDS TERMINATED BY "<>";

LOAD DATA LOCAL INFILE "kid_physical.dat"
INTO TABLE Kid_Physical
FIELDS TERMINATED BY "<>";

LOAD DATA LOCAL INFILE "meal_nutrit.dat"
INTO TABLE Meal_Nutrit
FIELDS TERMINATED BY "<>";

LOAD DATA LOCAL INFILE "disease.dat"
INTO TABLE Disease
FIELDS TERMINATED BY "<>";

LOAD DATA LOCAL INFILE "medical_history.dat"
INTO TABLE Medical_History
FIELDS TERMINATED BY "<>";


